export const projects = [
  {
    slug: 'venom-vape',
    name: 'Venom Vape',
    eyebrow: 'PACKAGING / BRANDING',
    intro: 'Brand identity, typography, packaging, characters, web banner and point-of-sale posters for Venom — “Let the flavour sink in.”',
    image: '/projects/venom-vape/venom-full.webp',
    thumb: '/projects/venom-vape/venom-thumb.png',
    alt: 'Venom Vape project: logo, typography, packaging, bottles, range, characters, web banner and POS posters',
  },
  {
    slug: 'vital-bloom',
    name: 'Vital Bloom',
    eyebrow: 'PACKAGING / BRANDING',
    intro: 'Brand identity, typography and packaging for Vital Bloom, a colourful range of daily supplements.',
    image: '/projects/vital-bloom/vital-bloom-full.webp',
    thumb: '/projects/vital-bloom/vital-bloom-thumb.png',
    alt: 'Vital Bloom project: logo, typography, packaging and the product range',
  },
  {
    slug: 'fresh',
    name: 'Fresh',
    eyebrow: 'WEB DESIGN / BRANDING',
    intro: 'Brand identity, can packaging and website design for Fresh Nutrition, a subscription drinks brand with weekly, monthly and yearly plans.',
    image: '/projects/fresh/fresh-full.webp',
    thumb: '/projects/fresh/fresh-thumb.png',
    alt: 'Fresh Nutrition project: logo, can range, website design and subscription plans',
  },
  {
    slug: 'ivg-pro',
    name: 'IVG Pro',
    eyebrow: 'PACKAGING / PRODUCT DESIGN',
    intro: 'Product photography and packaging artwork for the IVG Pro 10K disposable vape range, across its full range of flavours.',
    images: [
      { src: '/projects/ivg-pro/ivgpro-hero.webp', alt: 'IVG Pro logo and device render' },
      { src: '/projects/ivg-pro/ivgpro-range.webp', alt: 'IVG Pro 10K full flavour range packaging lineup' },
      { src: '/projects/ivg-pro/ivgpro-detail.webp', alt: 'Close-up detail of IVG Pro packaging and devices' },
    ],
    thumb: '/projects/ivg-pro/ivgpro-thumb.png',
  },
];
